# Use postgres/example user/password credentials
services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    volumes:
      - ./client:/app
    restart: unless-stopped
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 8080:8080
