version: "3.1"

services:
  app:
    image: pocketbook
    restart: always
    ports:
      - 3000:3000`

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: dbadmin
      POSTGRES_DB: pocketbook

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
